lang: en
title: Jekyll-Twitter-Theme
description: A twitter theme for Jekyll.

global:
  # site icon should have 1:1 aspect ratio
  site_icon: "https://avatars3.githubusercontent.com/u/3083652?s=200&v=4"
  base_url: ""
  nav:
    caption_home: "Home"
  profile:
    image:
      url: "https://avatars3.githubusercontent.com/u/3083652?s=200&v=4"
    name: "Jekyll Blog"
    id: "@jekyll_blog"
  post:
    default_thumbnail: "https://avatars3.githubusercontent.com/u/3083652?s=200&v=4"